export const staysDetailsData = {
  name: "Sixteen By Sixteen",
  stars: 4,
  address: "16 Kofo Abayomi Street, Victoria Island, 106104 Lagos, Nigeria",
  rating: 8.3,
  reviewCount: 112,
  ratingLabel: "Very good",
  locationScore: 9.0,
  coupleLocationScore: 9.6,
  description: {
    accommodations:
      "Sixteen By Sixteen in Lagos offers family rooms with air-conditioning, private bathrooms, and modern amenities. Guests enjoy free WiFi, a garden, and a bar for relaxation.",
    facilities:
      "The hotel provides private check-in and check-out, a paid shuttle service, wellness packages, and a concierge. Additional services include a shared kitchen, minimarket, daily housekeeping, and free on-site parking.",
    dining:
      "A continental breakfast with cheese and fruits is served daily. The outdoor seating area offers scenic views, while room service and a child-friendly buffet cater to all guests.",
    location:
      "Located 20 km from Murtala Muhammed International Airport, Sixteen By Sixteen is near attractions such as the National Museum Lagos (1.9 km) and Freedom Park Lagos (3.1 km). Highly rated by guests for its excellent service.",
  },
  highlights: [
    { icon: "📍", text: "Top location: Highly rated by recent guests" },
    { icon: "🌅", text: "Lake view rooms available" },
    { icon: "🅿️", text: "Free private parking available at the hotel" },
    { icon: "🍳", text: "Breakfast included: Continental" },
  ],
  popularFacilities: [
    "Airport shuttle",
    "Free WiFi",
    "Non-smoking rooms",
    "Room service",
    "Free parking",
    "Family rooms",
    "Tea/coffee maker in all rooms",
    "Bar",
    "Breakfast",
  ],
  images: [
    { alt: "Common area with plants and natural light", placeholder: "🌿" },
    { alt: "Bedroom with blue accents", placeholder: "🛏️" },
    { alt: "Bathroom with natural tones", placeholder: "🚿" },
    { alt: "Dining area", placeholder: "🍽️" },
    { alt: "Room interior", placeholder: "🛋️" },
    { alt: "Garden view", placeholder: "🌳" },
    { alt: "Bedroom suite", placeholder: "🏨" },
  ],
  rooms: [
    {
      id: 1,
      name: "Deluxe King Suite",
      availability: "1 left",
      bed: "1 large double bed",
      size: "27 m²",
      features: [
        "Private suite",
        "Garden view",
        "Inner courtyard view",
        "Air conditioning",
        "Ensuite bathroom",
        "Flat-screen TV",
        "Coffee machine",
        "Free WiFi",
      ],
      amenities: [
        "Free toiletries",
        "Bathrobe",
        "Safety deposit box",
        "Bidet",
        "Streaming service (like Netflix)",
        "Toilet",
        "Bath or shower",
        "Towels",
        "Linen",
        "Socket near the bed",
        "Desk",
        "TV",
        "Refrigerator",
        "Ironing facilities",
        "Tea/Coffee maker",
        "Iron",
        "Microwave",
        "Electric kettle",
        "Wardrobe or closet",
        "Oven",
        "Stovetop",
        "Toaster",
        "Clothes rack",
        "Toilet paper",
        "Board games/puzzles",
        "Books, DVDs, or music for children",
        "Carbon monoxide detector",
        "Single-room air conditioning for guest accommodation",
      ],
      choices: [
        "Continental breakfast included",
        "Total cost to cancel",
        "No prepayment needed – pay at the property",
      ],
      originalPrice: "NGN 166,001",
      currentPrice: "NGN 132,800",
      discount: "20% off",
      deal: "Early 2026 Deal",
      guests: 2,
    },
    {
      id: 2,
      name: "Deluxe King Suite (Single)",
      availability: null,
      bed: "1 large double bed",
      size: "27 m²",
      features: [
        "Private suite",
        "Garden view",
        "Air conditioning",
        "Ensuite bathroom",
        "Flat-screen TV",
        "Coffee machine",
        "Free WiFi",
      ],
      amenities: [
        "Free toiletries",
        "Bathrobe",
        "Safety deposit box",
        "Bidet",
        "Streaming service",
        "Bath or shower",
        "Towels",
        "Linen",
        "Desk",
        "TV",
        "Refrigerator",
        "Tea/Coffee maker",
        "Iron",
        "Microwave",
        "Electric kettle",
      ],
      choices: [
        "Continental breakfast included",
        "Total cost to cancel",
        "No prepayment needed – pay at the property",
      ],
      originalPrice: "NGN 149,401",
      currentPrice: "NGN 119,521",
      discount: "20% off",
      deal: "Early 2026 Deal",
      guests: 1,
    },
    {
      id: 3,
      name: "Budget Single Room",
      availability: "1 left",
      bed: "1 single bed",
      size: "15 m²",
      features: [
        "Room with shared bathroom",
        "High floor",
        "Lake view",
        "Air conditioning",
        "Flat-screen TV",
        "Coffee machine",
        "Free WiFi",
      ],
      amenities: [
        "Flat-screen TV",
        "Coffee machine",
        "Free WiFi",
        "Air conditioning",
        "Lake view",
      ],
      choices: [
        "Continental breakfast included",
        "Total cost to cancel",
        "No prepayment needed – pay at the property",
        "We have 1 left",
      ],
      originalPrice: "NGN 96,834",
      currentPrice: "NGN 77,467",
      discount: "20% off",
      deal: "Early 2026 Deal",
      guests: 1,
    },
  ],
  guestReviews: {
    overall: 8.3,
    totalReviews: 112,
    categories: [
      { name: "Staff", score: 8.9 },
      { name: "Facilities", score: 8.4 },
      { name: "Cleanliness", score: 8.6 },
      { name: "Comfort", score: 8.6 },
      { name: "Value for money", score: 8.5 },
      { name: "Location", score: 9.0 },
      { name: "Free WiFi", score: 8.8 },
    ],
    reviews: [
      {
        name: "Tukur",
        country: "Nigeria",
        flag: "🇳🇬",
        text: "The ambiance and the beautiful indoor scaping of the place. The icing on the cake is the kitchenette…I enjoyed my stay…",
      },
      {
        name: "Fiona",
        country: "South Africa",
        flag: "🇿🇦",
        text: "Breakfast wasn't great. But the staff and room were great. The water was hot, although the water pressure was not good.",
      },
      {
        name: "Santhosh",
        country: "India",
        flag: "🇮🇳",
        text: "The staff and location. It's bread and breakfast kind of stay with spacious.",
      },
    ],
    topics: ["Room", "Location", "Breakfast", "Quiet", "Bed"],
  },
  facilities: {
    bathroom: [
      "Toilet paper",
      "Towels",
      "Bidet",
      "Bath or shower",
      "Toilet",
      "Free toiletries",
      "Bathrobe",
      "Bath",
      "Shower",
    ],
    bedroom: ["Linen", "Wardrobe or closet"],
    view: ["View"],
    outdoors: ["Outdoor furniture", "Garden"],
    kitchen: [
      "Shared kitchen",
      "Coffee machine",
      "Toaster",
      "Stovetop",
      "Oven",
      "Electric kettle",
      "Microwave",
      "Refrigerator",
      "Tea/Coffee maker",
    ],
    internet: "WiFi is available in all areas and is free of charge.",
    parking:
      "Free private parking is possible on site (reservation is needed).",
    receptionServices: [
      "Invoice provided",
      "Lockers",
      "Private check-in/check-out",
      "Concierge service",
      "Luggage storage",
      "Tour desk",
      "Currency exchange",
      "Express check-in/check-out",
    ],
    familyFriendly: [
      "Family rooms",
      "Kid-friendly buffet",
      "Books, DVDs, or music for children",
      "Board games/puzzles",
    ],
    foodAndDrink: [
      { name: "Fruits", extra: "Additional charge" },
      { name: "Wine/champagne", extra: "Additional charge" },
      { name: "Snack bar", extra: null },
      { name: "Bar", extra: "Additional charge" },
    ],
    safety: [
      "Fire extinguishers",
      "CCTV outside property",
      "CCTV in common areas",
      "Smoke alarms",
      "Security alarm",
      "Key card access",
      "Key access",
      "24-hour security",
      "Safety deposit box",
    ],
    general: [
      { name: "Shuttle service", extra: "Additional charge" },
      { name: "Carbon monoxide detector", extra: null },
      { name: "Minimarket on site", extra: null },
      { name: "Designated smoking area", extra: null },
      { name: "Air conditioning", extra: null },
      { name: "Non-smoking throughout", extra: null },
      { name: "Car hire", extra: null },
      { name: "Lift", extra: null },
      { name: "Ironing facilities", extra: null },
      { name: "Airport shuttle", extra: "Additional charge" },
      { name: "Non-smoking rooms", extra: null },
      { name: "Iron", extra: null },
      { name: "Room service", extra: "Additional charge" },
    ],
    roomAmenities: ["Socket near the bed", "Clothes rack"],
    activities: [{ name: "Walking tours", extra: "Additional charge" }],
    livingArea: ["Desk"],
    cleaning: [
      { name: "Daily housekeeping", extra: null },
      { name: "Ironing service", extra: "Additional charge" },
      { name: "Dry cleaning", extra: "Additional charge" },
      { name: "Laundry", extra: "Additional charge" },
    ],
    business: [
      { name: "Fax/photocopying", extra: null },
      { name: "Meeting/banquet facilities", extra: "Additional charge" },
    ],
    wellness: [
      { name: "Full body massage", extra: null },
      { name: "Hand massage", extra: null },
      { name: "Head massage", extra: null },
      { name: "Couples massage", extra: null },
      { name: "Foot massage", extra: null },
      { name: "Neck massage", extra: null },
      { name: "Back massage", extra: null },
      { name: "Spa/wellness packages", extra: null },
      { name: "Massage", extra: "Additional charge" },
    ],
    languages: ["English", "French"],
  },
  houseRules: {
    checkIn: "From 14:00 to 22:00",
    checkOut: "From 11:00 to 12:00",
    cancellation:
      "Cancellation and prepayment policies vary according to accommodation type. Please check what conditions may apply to each option when making your selection.",
    children: "Children of any age are welcome.",
    cotPolicy: "Cots and extra beds are not available at this property.",
    ageRestriction: "The minimum age for check-in is 18",
    pets: "Pets are not allowed.",
    paymentMethods: ["Visa", "Mastercard", "ATM card", "Cash"],
    parties: "Parties/events are not allowed",
    finePrint:
      "This property will not accommodate hen, stag or similar parties.",
  },
  faqs: [
    {
      question: "What kind of breakfast is served at Sixteen By Sixteen?",
      answer:
        "Please contact the property directly for the most accurate and up-to-date information about this question.",
    },
    {
      question: "What type of room can I book at Sixteen By Sixteen?",
      answer:
        "Please contact the property directly for the most accurate and up-to-date information about this question.",
    },
    {
      question:
        "What are the check-in and check-out times at Sixteen By Sixteen?",
      answer:
        "Please contact the property directly for the most accurate and up-to-date information about this question.",
    },
    {
      question: "How much does it cost to stay at Sixteen By Sixteen?",
      answer:
        "Please contact the property directly for the most accurate and up-to-date information about this question.",
    },
    {
      question: "What is there to do at Sixteen By Sixteen?",
      answer:
        "Please contact the property directly for the most accurate and up-to-date information about this question.",
    },
    {
      question: "How far is Sixteen By Sixteen from the centre of Lagos?",
      answer:
        "Please contact the property directly for the most accurate and up-to-date information about this question.",
    },
  ],
};
